name: Enhancement Report
description: File a suggestion for an enhancement
title: "[Enhancement suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your input, your suggestions are very useful to us!
  - type: textarea
    id: Suggestion
    attributes:
      label: Enhancement suggestion
      description: What is your suggestion, and why would it be useful to you?
      placeholder: "My suggestion for an enhancement is..."
    validations:
      required: true
