name: HyLoRD Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          libpthread-stubs0-dev

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Make
      run: |
        make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$PWD/install

    - name: Install 
      run: |
        make install
        
    - name: Verify installation
      run: |
        find ./install -name hylord -type f
