name: Build and Deploy documentation

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          libpthread-stubs0-dev \
          doxygen \
          graphviz

    - uses: actions/checkout@v4

    - name: Build
      run: |
        make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$PWD/install

    - name: Install 
      run: |
        make install

    - name: Verify installation
      run: |
        $(find ./install -name hylord -type f) --version

    - name: Add TOC to doxygen main page
      run: |
        sed -i '2i\\\tableofcontents' README.md

    - name: Generate docs 
      run: |
        make docs || doxygen build/docs/HyLoRD.doxyfile

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/docs/html/

  deploy:
    needs: build-and-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
