name: Documentation

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  generate-docs:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: hylord-build
          
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: |
          make docs || doxygen build/docs/HyLoRD.doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html
          keep_files: false
