name: HyLoRD test

on:
  push:
    branches : [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          git \
          libpthread-stubs0-dev

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: test 
      run: |
        make test CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$PWD/install

